//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentMode
    {
        public CurrentMode()
        {
            this.CurrentWeapons = new HashSet<CurrentWeapon>();
        }
    
        public int Id { get; set; }
        public string Mode { get; set; }
    
        public virtual ICollection<CurrentWeapon> CurrentWeapons { get; set; }
    }
}
