//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentWeapon
    {
        public CurrentWeapon()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public string ClassName { get; set; }
        public int CurrentModeId { get; set; }
    
        public virtual ICollection<Player> Players { get; set; }
        public virtual CurrentMode CurrentMode { get; set; }
    }
}
