//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.AbstractContainers = new HashSet<AbstractContainer>();
        }
    
        public int Id { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<AbstractContainer> AbstractContainers { get; set; }
    }
}
