//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoadoutModelContainer : DbContext
    {
        public LoadoutModelContainer()
            : base("name=LoadoutModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerInfo> PlayerInfos { get; set; }
        public virtual DbSet<CurrentWeapon> CurrentWeapons1 { get; set; }
        public virtual DbSet<Loadout> Loadouts { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<AbstractContainer> AbstractContainers { get; set; }
        public virtual DbSet<CurrentMode> CurrentModes { get; set; }
    }
}
