//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loadout
    {
        public Loadout()
        {
            this.AssignableItems = new HashSet<AssignableItem>();
        }
    
        public int Id { get; set; }
    
        public virtual Uniform Uniform { get; set; }
        public virtual HandgunWeapon HandgunWeapon { get; set; }
        public virtual SecondaryWeapon SecondaryWeapon { get; set; }
        public virtual PrimaryWeapon PrimaryWeapon { get; set; }
        public virtual Backpack Backpack { get; set; }
        public virtual Vest Vest { get; set; }
        public virtual ICollection<AssignableItem> AssignableItems { get; set; }
    }
}
