//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string PlayerUID { get; set; }
    
        public virtual PlayerInfo PlayerInfo { get; set; }
        public virtual CurrentWeapon CurrentWeapon { get; set; }
        public virtual Loadout Loadout { get; set; }
    }
}
