//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryWeapon : AbstractWeapon
    {
        public PrimaryWeapon()
        {
            this.Loadouts = new HashSet<Loadout>();
            this.PrimaryWeaponItems = new HashSet<PrimaryWeaponItem>();
        }
    
    
        public virtual ICollection<Loadout> Loadouts { get; set; }
        public virtual ICollection<PrimaryWeaponItem> PrimaryWeaponItems { get; set; }
    }
}
