//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastelandA23.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondaryWeaponItem : AbstractWeaponItem
    {
        public int SecondaryWeaponId { get; set; }
    }
}
